name: Dependency Audit

on:
  schedule:
    - cron: '0 2 * * 0' # Run every Sunday at 2 AM
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install safety

    - name: Run safety check
      run: safety check -r requirements.txt
